### PR TITLE
[FEATURE] Pass SENTRY_SERVER_NAME environment variable to Sentry

### PR DESCRIPTION
**Pull request by cweiske**

### CODE REVIEW

**Comment by christophlehmann** [comment]
Thanks for the PR, but i won't merge it, because we don't use that flag and the environment variable is not an official coming with the SDK.

With the next release you can set it pretty easily like `$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['sentry_client']['options']['server_name'] = 'your server name';`

**Comment by cweiske** [comment]
Then please cherry-pick the doc URL fix commit.

**Comment by cweiske** [comment]
oh, you did :)

**Comment by cweiske** [comment]
@christophlehmann is it true that I can use 
```
$GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['sentry_client']['options']['server_name'] = 'your server name';
``` 
now with 4.3.0?
I don't see that in the code.

Also, it should probably be 
```
$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['sentry_client']['options']['server_name'] = 'your server name';
```
(`EXTENSIONS` instead of `EXTCONF`)

**Comment by christophlehmann** [comment]
>now with 4.3.0?

Not yet. With upcoming release, see https://github.com/networkteam/sentry_client/pull/76

>(EXTENSIONS instead of EXTCONF)

Its intended to use `EXTCONF`, because its form is free while `EXTENSIONS` streamlines variables from `ext_conf_template.txt`

**Pull request closed without merging**
